# Generated by Django 4.2.6 on 2023-10-17 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_matchresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchresult',
            name='total_points',
        ),
    ]
