# Generated by Django 4.2.6 on 2023-10-17 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.group'),
        ),
    ]
