# Generated by Django 4.2.6 on 2023-10-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_group_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchresult',
            name='group',
        ),
        migrations.AddField(
            model_name='matchresult',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='match_results', to='tournaments.group'),
        ),
    ]
