# Generated by Django 4.2.6 on 2023-10-17 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_remove_matchresult_group_matchresult_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='winning_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_wins', to='tournaments.team'),
        ),
    ]
