# Generated by Django 4.2.6 on 2023-10-17 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_remove_matchresult_groups_remove_matchresult_map_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchresult',
            name='winning_team',
        ),
        migrations.AddField(
            model_name='matchschedule',
            name='winning_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_wins', to='tournaments.team'),
        ),
    ]
