# Generated by Django 4.2.6 on 2023-10-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0012_overallstandings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchresult',
            name='match_number',
        ),
        migrations.AddField(
            model_name='matchschedule',
            name='match_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
